### PR TITLE
Added requirements.yml files

### PR DESCRIPTION
**Pull request by umeboshi2**
I am opening issue in debops to discuss this.  BBS with link.

### CODE REVIEW

**Comment by umeboshi2** [comment]
https://github.com/debops/debops/issues/140

**Comment by ypid** [comment]
Maybe a good idea to write small scripts for that stuff? Since doing something (added new roles) will get more complex the more files we need to update and so on.

**Comment by drybjed** [comment]
I'm adding roles manually, modification of requirements files isn't that big of an issue for me. And I guess the `-testing` requirements could be removed at some point, unless we find a use for multiple requirements files in a `git` repository, which I doubt.

**Comment by umeboshi2** [comment]
The requirements file can be shorter, since ansible-galaxy will also install dependencies defined in a role.

**Pull request merged**
